### ISSUE TITLE
allauth language

### ISSUE THREAD

**Issue by jadyndev** [luto/crowdprinter#10]
Die Login/Logout/... Seiten von allauth sind nur auf englisch, der rest der Seite auf Deutsch. Es sollte alls einheitlich sein.

**Comment by luto** [comment]
Unsere eigenen Texte sind nicht übersetzt, allauth schon. `LANGUAGE_CODE = "de"` in der Config macht alles einheitlich Deutsch. Alles einheitlich Englisch geht nur, wenn wir alle unsere Texte übersetzen, was glaub ich zumindest vor dem c3 nicht passieren wird?
